name: Test

on:
  push:
  pull_request:

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - redmine-repository: 'redmica/redmica'
            redmine-version: 'stable-3.0'
            ruby-version: '3.3'
          - redmine-repository: 'redmica/redmica'
            redmine-version: 'master'
            ruby-version: '3.3'
          - redmine-repository: 'redmine/redmine'
            redmine-version: 'master'
            ruby-version: '3.3'

    steps:
    - uses: hidakatsuya/action-setup-redmine@v1
      with:
        repository: ${{ matrix.redmine-repository }}
        version: ${{ matrix.redmine-version }}
        ruby-version: ${{ matrix.ruby-version }}
        database: 'postgres:14'

    - uses: actions/checkout@v4
      with:
        path: plugins/redmine_ip_filter

    - run: |
        bin/rails redmine:plugins:test NAME=redmine_ip_filter
